package com.mathi.finance.features.contacts.data.repository

import com.mathi.finance.core.network.SupabaseClient
import com.mathi.finance.features.contacts.data.local.ContactDao
import com.mathi.finance.features.contacts.data.local.ContactEntity
import com.mathi.finance.features.contacts.domain.model.Contact
import io.github.jan.supabase.postgrest.from
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map

class ContactRepository(
    private val contactDao: ContactDao
) {
    val contacts: Flow<List<Contact>> = contactDao.getAllContacts().map { entities ->
        entities.map { it.toDomain() }
    }

    suspend fun saveContactsLocally(contacts: List<Contact>, createdBy: Int) {
        val entities = contacts.map { it.toEntity(createdBy) }
        contactDao.insertContacts(entities)
    }

    suspend fun syncWithRemote(createdBy: Int) {
        val unsynced = contactDao.getUnsyncedContacts()
        if (unsynced.isEmpty()) return

        try {
            val contactsToSync = unsynced.map { it.toDomain().copy(created_by = createdBy) }
            
            // Fetch existing to avoid duplicates as previously implemented
            val response = SupabaseClient.client.from("contacts")
                .select {
                    filter {
                        eq("created_by", createdBy)
                    }
                }
                .decodeList<Contact>()

            val existingNumbers = response.mapNotNull { it.phoneNumber }.toSet()
            val filteredContacts = contactsToSync.filter { it.phoneNumber != null && it.phoneNumber !in existingNumbers }

            if (filteredContacts.isNotEmpty()) {
                SupabaseClient.client.from("contacts").insert(filteredContacts)
            }
            
            contactDao.markAsSynced(unsynced.map { it.id })
        } catch (e: Exception) {
            e.printStackTrace()
            throw e
        }
    }

    private fun ContactEntity.toDomain() = Contact(
        id = null, // ID is generated by Supabase
        name = name,
        phoneNumber = phoneNumber,
        created_by = createdBy
    )

    private fun Contact.toEntity(createdBy: Int) = ContactEntity(
        id = name + phoneNumber, // Simple composite ID for local storage
        name = name,
        phoneNumber = phoneNumber,
        createdBy = createdBy,
        isSynced = false
    )
}
