package com.mathi.finance.features.contacts.data.repository

import com.mathi.finance.core.network.SupabaseClient
import com.mathi.finance.core.prefs.PreferenceManager
import com.mathi.finance.features.contacts.data.local.ContactDao
import com.mathi.finance.features.contacts.data.local.ContactEntity
import com.mathi.finance.features.contacts.domain.model.Contact
import com.mathi.finance.features.contacts.domain.repository.ContactRepository
import io.github.jan.supabase.postgrest.from
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map

class ContactRepositoryImpl(
    private val contactDao: ContactDao,
    preferenceManager: PreferenceManager
) : ContactRepository {
    private val currentUserId = preferenceManager.getUserId()

    override val contacts: Flow<List<Contact>> = contactDao.getAllContacts().map { entities ->
        entities.map { it.toDomain() }
    }

    override suspend fun saveContactsLocally(contacts: List<Contact>) {
        if (currentUserId == -1) return
        val entities = contacts.map { it.toEntity(currentUserId) }
        contactDao.insertContacts(entities)
    }

    override suspend fun syncWithRemote() {
        if (currentUserId == -1) return
        val unsynced = contactDao.getUnsyncedContacts()
        if (unsynced.isEmpty()) return

        try {
            val contactsToSync = unsynced.map { it.toDomain().copy(created_by = currentUserId) }
                .filter { !it.phoneNumber.isNullOrBlank() }

            SupabaseClient.client.from("contacts").upsert(contactsToSync) {
                onConflict = "phone_number,name,created_by"
            }
            contactDao.markAsSynced(unsynced.map { it.id })
        } catch (e: Exception) {
            e.printStackTrace()
            throw e
        }
    }

    private fun ContactEntity.toDomain() = Contact(
        id = null, // ID is generated by Supabase
        name = name,
        phoneNumber = phoneNumber,
        created_by = createdBy
    )

    private fun Contact.toEntity(createdBy: Int) = ContactEntity(
        id = name + phoneNumber, // Simple composite ID for local storage
        name = name,
        phoneNumber = phoneNumber,
        createdBy = createdBy,
        isSynced = false
    )
}
